'use client';

import Link from 'next/link';
import { useCallback, useEffect, useMemo, useState } from 'react';

type ProductionOrder = { number: string; eventDate: string; customer: string; dessert: string; status: string; amountRubles: number | null; weightGrams: number | null; decor: string; priority: number; assignee: string | null };
const rubles = new Intl.NumberFormat('ru-RU', { style: 'currency', currency: 'RUB', maximumFractionDigits: 0 });
const statusLabels: Record<string, string> = { new: 'Новый', assigned: 'Назначен', contacted: 'Связались', qualified: 'Уточнение', calculation: 'Расчёт', approval: 'Согласование', awaiting_payment: 'Ожидает оплату', paid: 'Оплачен', production: 'В производстве', ready: 'Готов', completed: 'Выдан' };

export default function ProductionPage() {
  const [orders, setOrders] = useState<ProductionOrder[]>([]); const [error, setError] = useState('');
  const load = useCallback(async () => { try { const response = await fetch('/api/backend/crm/production'); const data = await response.json(); if (!response.ok) throw new Error(data.detail); setOrders(data.orders); } catch (failure) { setError(failure instanceof Error ? failure.message : 'Не удалось загрузить календарь.'); } }, []);
  useEffect(() => { const timer = window.setTimeout(() => void load(), 0); return () => clearTimeout(timer); }, [load]);
  const days = useMemo(() => { const grouped = new Map<string, ProductionOrder[]>(); for (const order of orders) grouped.set(order.eventDate, [...(grouped.get(order.eventDate) ?? []), order]); return [...grouped.entries()]; }, [orders]);
  return <main className="crm-page"><header className="crm-header"><div className="crm-brand"><span className="crm-brand-mark">СИ</span><span><h1>Производство</h1><small>Календарь заказов и загрузки</small></span></div><nav className="crm-nav"><Link href="/crm">Заявки</Link><Link className="active" href="/crm/production">Производство</Link><Link href="/crm/analytics">Аналитика</Link><Link href="/crm/team">Команда</Link></nav><button className="crm-refresh" onClick={() => void load()}>Обновить</button></header><section className="crm-workspace production-calendar">{error && <div className="crm-alert">{error}</div>}{days.map(([day, items]) => <section className="production-day" key={day}><header><div><small>{new Date(`${day}T12:00:00`).toLocaleDateString('ru-RU', { weekday: 'long' })}</small><h2>{new Date(`${day}T12:00:00`).toLocaleDateString('ru-RU', { day: 'numeric', month: 'long' })}</h2></div><b>{items.length} заказов · {(items.reduce((sum, item) => sum + (item.weightGrams ?? 0), 0) / 1000).toLocaleString('ru-RU')} кг</b></header><div>{items.map((item) => <Link className={`production-order priority-${item.priority}`} href={`/crm?order=${encodeURIComponent(item.number)}`} key={item.number}><strong>{item.number}</strong><span><b>{item.dessert}</b><small>{item.customer} · {item.assignee ?? 'без ответственного'}</small><small>{item.weightGrams ? `${(item.weightGrams / 1000).toLocaleString('ru-RU')} кг` : 'вес не указан'} · {item.decor || 'декор не указан'}</small></span><span><b>{item.amountRubles == null ? 'цена не указана' : rubles.format(item.amountRubles)}</b><small>{statusLabels[item.status] ?? item.status}</small></span></Link>)}</div></section>)}{!days.length && <div className="crm-empty">В ближайшем периоде заказов нет.</div>}</section></main>;
}
